name: ✨ Idée / fonctionnalité
description: Proposer une amélioration
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: L'idée
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Pourquoi ?
